# Exercise - Infrastructure Creation
AWSTemplateFormatVersion: 2010-09-09
Description: >
 Kelvin Isievwore / Exercise: Infrastructure Creation
 Template to Deploy an EC2Instance with SecurityGroup Using CloudFormation.

Resources:
  EC2Instance:
   Type: 'AWS::EC2::Instance'
   Properties:
     SecurityGroups:
       - !Ref InstanceSecurityGroup
     KeyName: udacity  
     ImageId: 'ami-09e67e426f25ce0d7' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
     InstanceType: t2.micro

  InstanceSecurityGroup:
   Type: 'AWS::EC2::SecurityGroup'
   Properties:
     GroupDescription: Enable SSH access via port 22
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: '22'
         ToPort: '22'
         CidrIp: 0.0.0.0/0
