# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - run: echo "Hello" # This prints "Hello" to stdout.
  print_world: # This is our second job.
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - run: echo " World." # This prints "World" to stdout.
workflows:
  # Name the workflow "one_and_two"
  one_and_two:
    # Run both jobs in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
